"""Tests for real_api_smoke.py."""

from __future__ import annotations

import json
import os
from unittest.mock import patch, MagicMock
from pathlib import Path

from scripts.real_api_smoke import main

def test_smoke_skips_cleanly_without_api_key(tmp_path: Path) -> None:
    """Verify script skips cleanly and returns 0 when no API key is available."""
    results_file = tmp_path / "real_api_smoke_results.json"
    
    with patch("scripts.real_api_smoke.RESULTS_PATH", results_file), \
         patch.dict(os.environ, {"GEMINI_API_KEY": ""}, clear=True):
         
        exit_code = main()
        assert exit_code == 0
        assert results_file.exists()
        
        data = json.loads(results_file.read_text(encoding="utf-8"))
        assert data["status"] == "SKIPPED"

def test_exit_zero_on_skip(tmp_path: Path) -> None:
    """Verify main returns 0 when skipped due to placeholder API key."""
    results_file = tmp_path / "real_api_smoke_results.json"
    
    with patch("scripts.real_api_smoke.RESULTS_PATH", results_file), \
         patch.dict(os.environ, {"GEMINI_API_KEY": "your_gemini_api_key_here"}):
         
        exit_code = main()
        assert exit_code == 0
        assert results_file.exists()
        
        data = json.loads(results_file.read_text(encoding="utf-8"))
        assert data["status"] == "SKIPPED"

def test_results_json_schema_valid(tmp_path: Path) -> None:
    """Verify the schema of results JSON generated by the smoke test."""
    results_file = tmp_path / "real_api_smoke_results.json"
    
    with patch("scripts.real_api_smoke.RESULTS_PATH", results_file), \
         patch.dict(os.environ, {"GEMINI_API_KEY": "your_gemini_api_key_here"}):
         
        exit_code = main()
        assert exit_code == 0
        assert results_file.exists()
        
        data = json.loads(results_file.read_text(encoding="utf-8"))
        assert "timestamp" in data
        assert data["provider"] == "gemini"
        assert "tests_passed" in data
        assert "tests_failed" in data
        assert "total_tokens_used" in data
        assert "total_cost_usd" in data
        assert "latency_ms_avg" in data

def test_budget_enforcement_without_api_call() -> None:
    """Verify that budget limit enforcement prevents any real API call."""
    from core.model_provider import GeminiProvider
    from core.observability.token_budget import TokenBudget
    
    provider = GeminiProvider(agent_name="clone")
    
    custom_budgets = {
        "test_agent": {
            "hard_limit_per_call": 10
        }
    }
    tb_test = TokenBudget(state_dir=Path(".projectos_state"), budgets=custom_budgets)
    
    with patch.object(provider, "_complete_once") as mock_complete_once:
        prompt_50_tokens = "A" * 200
        response = provider.complete(
            prompt=prompt_50_tokens,
            system_prompt="",
            max_tokens=5,
            agent_name="test_agent",
            token_budget=tb_test
        )
        
        assert "TOKEN_BUDGET_EXCEEDED" in response
        mock_complete_once.assert_not_called()
