"""Planning Agent implementation for ProjectOS."""

from __future__ import annotations

import json
import logging
import os
import tempfile
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, List, Mapping, Optional, Sequence, TYPE_CHECKING

from core.base_agent import BaseAgent
from core.events import AgentEvent, AgentResult, EventPriority, EventType
from core.intelligence.collaboration import ConsultationType
from core.model_provider import ModelProvider
from core.project_context import ProjectContextLoader

if TYPE_CHECKING:
    from core.intelligence.collaboration import CollaborationBroker
    from core.intelligence.context_retriever import ContextRetriever
    from core.intelligence.memory_manager import MemoryManager


AGENT_NAME = "planning"
ROLE_DESCRIPTION = "Feature decomposition and backlog planning agent."
DEFAULT_PROJECT_ROOT = Path(__file__).resolve().parents[1]

ENCODING = "utf-8"
EMPTY_TEXT = ""
FILE_WRITE_MODE = "w"
NEWLINE = "\n"
SPACE = " "
TEMP_PREFIX = "."
TEMP_SUFFIX = ".tmp"

BACKLOG_FILE_NAME = "backlog.md"
DECISIONS_LOG_NAME = "decisions.log"

# Global SYSTEM_PROMPT removed (defined as class attribute instead)
MEMORY_SYSTEM_PROMPT_TEMPLATE = (
    "{system_prompt}\n\n"
    "Similar planning decisions from this project:\n{memories}"
)
PROMPT_DESCRIPTION_LABEL = "Feature description:"
PROMPT_CONTEXT_LABEL = "Project context:"
PROMPT_CODEBASE_CONTEXT_LABEL = "Codebase context:"
PROMPT_INSTRUCTION = "Return a JSON array of task objects."
PROMPT_SECTION_SEPARATOR = "\n\n"

PAYLOAD_KEY_DESCRIPTION = "description"
PAYLOAD_KEY_PROJECT_CONTEXT = "project_context"
PAYLOAD_KEY_FILE_PATH = "file_path"
PAYLOAD_KEY_TASK_DESCRIPTION = "task_description"
PAYLOAD_KEY_TASK_ID = "task_id"
PAYLOAD_KEY_TASK_TYPE = "task_type"
PAYLOAD_KEY_TARGET_AGENT = "target_agent"

MODEL_KEY_TASKS = "tasks"
MODEL_KEY_ID = "id"
MODEL_KEY_TITLE = "title"
MODEL_KEY_TYPE = "type"
MODEL_KEY_PRIORITY = "priority"
MODEL_KEY_ESTIMATED_COMPLEXITY = "estimated_complexity"
MODEL_KEY_FILE_PATH = "file_path"
MODEL_KEY_COMPLEXITY = "complexity"
MODEL_KEY_DEPENDENCIES = "dependencies"
MODEL_KEY_ACCEPTANCE_CRITERIA = "acceptance_criteria"
MODEL_KEY_AGENT_ASSIGNMENT = "agent_assignment"
MODEL_KEY_BLOCKED_BY = "blocked_by"

TASK_STATUS_PENDING = "PENDING"
TASK_STATUS_BLOCKED = "BLOCKED"
TASK_ID_PREFIX = "PLAN"
TASK_ID_SEPARATOR = "-"
TASK_SEQUENCE_WIDTH = 3

TASK_TYPE_FEATURE = "feature"
TASK_TYPE_BUG = "bug"
TASK_TYPE_REFACTOR = "refactor"
TASK_TYPE_TEST = "test"
TASK_TYPE_DOCS = "docs"
DEFAULT_TASK_TYPE = TASK_TYPE_FEATURE
VALID_TASK_TYPES = frozenset(
    {
        TASK_TYPE_FEATURE,
        TASK_TYPE_BUG,
        TASK_TYPE_REFACTOR,
        TASK_TYPE_TEST,
        TASK_TYPE_DOCS,
    }
)

PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"
VALID_PRIORITIES = frozenset({PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW})
DEFAULT_PRIORITY = PRIORITY_MEDIUM

COMPLEXITY_SMALL = "S"
COMPLEXITY_MEDIUM = "M"
COMPLEXITY_LARGE = "L"
COMPLEXITY_EXTRA_LARGE = "XL"
VALID_COMPLEXITIES = frozenset(
    {
        COMPLEXITY_SMALL,
        COMPLEXITY_MEDIUM,
        COMPLEXITY_LARGE,
        COMPLEXITY_EXTRA_LARGE,
    }
)
DEFAULT_COMPLEXITY = COMPLEXITY_MEDIUM

DEFAULT_AGENT_ASSIGNMENT = "planning_agent"
MODEL_MAX_TOKENS = 4096
DEFAULT_WORKFLOW_SUCCESS_RATE = 0.7
MAX_WORKFLOW_NAME_LENGTH = 50

BACKLOG_TITLE = "# ProjectOS Backlog"
BACKLOG_LAST_UPDATED_LABEL = "Last updated:"
BACKLOG_PRIORITY_HEADING_TEMPLATE = "## {priority} Priority"
BACKLOG_TASK_HEADING_TEMPLATE = "### [{task_id}] {title}"
BACKLOG_TYPE_LABEL = "- Type:"
BACKLOG_COMPLEXITY_LABEL = "- Complexity:"
BACKLOG_AGENT_LABEL = "- Agent:"
BACKLOG_ACCEPTANCE_LABEL = "- Acceptance:"
BACKLOG_CHECKLIST_PREFIX = "  - [ ]"
BACKLOG_DEPENDENCIES_LABEL = "- Dependencies:"
BACKLOG_STATUS_LABEL = "- Status:"
BACKLOG_NONE_VALUE = "None"
BACKLOG_BLOCKED_BY_LABEL = "- Blocked By:"

DECISION_LOG_PREFIX = "["
DECISION_LOG_SEPARATOR = "] ["
DECISION_LOG_SUFFIX = "]\n"
DECISION_SUCCESS = "SUCCESS"
DECISION_FAILURE = "FAILURE"
DECISION_REASON_CREATED_BACKLOG = "created backlog tasks from feature description"
DECISION_REASON_INVALID_EVENT = "planning agent received unsupported event type"
DECISION_REASON_INVALID_PAYLOAD = "planning event missing description"
DECISION_REASON_INVALID_JSON = "model returned invalid planning JSON"
LOGGER_ERROR_FORMAT = "%s: %s"

OUTPUT_KEY_TASKS = "tasks"
OUTPUT_KEY_ERROR = "error"
TARGET_CODE_REVIEW_AGENT = "code_review"
IMPLEMENTABILITY_WARNING_PREFIX = "⚠ Review note:"
NOT_IMPLEMENTABLE_TEXT = "not implementable"
MISSING_TEXT = "missing"
REVIEW_NOTE_LIMIT = 200


@dataclass
class Task:
    """Structured backlog task generated by the Planning Agent."""

    id: str
    title: str
    type: str
    priority: str
    complexity: str
    dependencies: List[str]
    acceptance_criteria: List[str]
    agent_assignment: str
    blocked_by: Optional[str]
    file_path: Optional[str]
    created_at: str
    status: str
    parent_task_id: Optional[str] = None

    def to_dict_str(self) -> str:
        """Return a JSON string representation of the task dictionary."""
        return json.dumps(asdict(self), indent=2)

    def to_markdown(self) -> str:
        """Render this task as compact markdown for agent consultation."""
        dependencies = (
            ", ".join(self.dependencies) if self.dependencies else BACKLOG_NONE_VALUE
        )
        acceptance_lines = [
            f"{BACKLOG_CHECKLIST_PREFIX} {criterion}"
            for criterion in self.acceptance_criteria
        ]
        lines = [
            BACKLOG_TASK_HEADING_TEMPLATE.format(task_id=self.id, title=self.title),
            f"{BACKLOG_TYPE_LABEL} {self.type}",
            f"{BACKLOG_COMPLEXITY_LABEL} {self.complexity}",
            f"{BACKLOG_AGENT_LABEL} {self.agent_assignment}",
            BACKLOG_ACCEPTANCE_LABEL,
            *acceptance_lines,
            f"{BACKLOG_DEPENDENCIES_LABEL} {dependencies}",
            f"{BACKLOG_STATUS_LABEL} {self.status}",
        ]
        if self.blocked_by:
            lines.append(f"{BACKLOG_BLOCKED_BY_LABEL} {self.blocked_by}")
        return NEWLINE.join(lines)


def _utc_timestamp() -> str:
    """Return an ISO-8601 UTC timestamp."""
    return datetime.now(timezone.utc).isoformat()


def _date_stamp() -> str:
    """Return a UTC date stamp for deterministic task IDs."""
    return datetime.now(timezone.utc).strftime("%Y%m%d")


def _write_atomically(path: Path, content: str) -> None:
    """Write content to a path by replacing it with a temporary file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f"{TEMP_PREFIX}{path.name}.",
        suffix=TEMP_SUFFIX,
        dir=str(path.parent),
    )
    try:
        with os.fdopen(
            file_descriptor,
            FILE_WRITE_MODE,
            encoding=ENCODING,
        ) as temporary_file:
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        os.replace(temporary_name, path)
    except Exception:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)
        raise


def _append_atomically(path: Path, content: str) -> None:
    """Append content to a file while preserving existing content."""
    existing_content = path.read_text(encoding=ENCODING) if path.exists() else EMPTY_TEXT
    _write_atomically(path, f"{existing_content}{content}")


class PlanningAgent(BaseAgent):
    """Agent that decomposes feature descriptions into backlog tasks."""

    SYSTEM_PROMPT = """You are a senior engineering project manager.
Your role is to decompose feature requests into small,
executable engineering tasks.

ALWAYS:
- Break work into tasks that touch ONE file maximum
- Write explicit acceptance criteria for each task
- Mark dependencies accurately
- Assign complexity: S (< 2 hours) or M (< 4 hours) only
- Never assign L or XL — split instead

NEVER:
- Create tasks that require changing 3+ files simultaneously
- Create tasks without acceptance criteria
- Assume unstated requirements
- Plan beyond the current phase

Output format: Valid JSON only. No markdown. No explanation.
{project_context}"""


    def __init__(
        self,
        model_provider: ModelProvider,
        logger: logging.Logger,
        project_root: Path | str = DEFAULT_PROJECT_ROOT,
        context_retriever: Optional["ContextRetriever"] = None,
        memory_manager: Optional["MemoryManager"] = None,
        collaboration_broker: Optional["CollaborationBroker"] = None,
        context_loader: Optional[ProjectContextLoader] = None,
    ) -> None:
        """Initialize PlanningAgent with model access and project paths."""
        super().__init__(
            AGENT_NAME,
            ROLE_DESCRIPTION,
            model_provider,
            logger,
            context_retriever=context_retriever,
            memory_manager=memory_manager,
            collaboration_broker=collaboration_broker,
            context_loader=context_loader,
        )
        self.project_root = Path(project_root)

    def handle(self, event: AgentEvent) -> AgentResult:
        """Handle a feature planning event and emit backlog updates."""
        self.update_consultation_depth(event)
        if event.event_type not in (EventType.NEW_FEATURE, EventType.MANUAL_TRIGGER):
            return self._failure_result(event, DECISION_REASON_INVALID_EVENT)

        description = event.payload.get(PAYLOAD_KEY_DESCRIPTION)
        if not isinstance(description, str) or not description.strip():
            return self._failure_result(event, DECISION_REASON_INVALID_PAYLOAD)

        clean_description = description.strip()
        project_context = event.payload.get(PAYLOAD_KEY_PROJECT_CONTEXT)
        memories = self.recall_relevant(query=clean_description, k=3)
        codebase_context = self.get_context(task_description=clean_description)
        prompt = self._build_prompt(
            clean_description,
            project_context if isinstance(project_context, str) else None,
            codebase_context,
        )

        system_prompt = self.build_system_prompt(self.SYSTEM_PROMPT)
        if memories:
            system_prompt = MEMORY_SYSTEM_PROMPT_TEMPLATE.format(
                system_prompt=system_prompt,
                memories=memories,
            )

        params = self.get_model_params()
        model_output = self.model_provider.complete(
            prompt,
            system_prompt,
            params["max_tokens"],
            temperature=params["temperature"],
            top_p=params["top_p"],
            agent_name=self.name,
        )
        try:
            tasks = self.parse_tasks(model_output)
        except ValueError as error:
            self.logger.error(LOGGER_ERROR_FORMAT, DECISION_REASON_INVALID_JSON, error)
            return self._failure_result(event, DECISION_REASON_INVALID_JSON)

        from core.task_decomposer import TaskDecomposer
        decomposer = TaskDecomposer(self.model_provider)
        all_tasks = decomposer.decompose_batch(tasks)
        self.logger.info(
            f"Planning complete: {len(tasks)} original tasks "
            f"→ {len(all_tasks)} after decomposition"
        )
        tasks = all_tasks

        self._consult_for_extra_large_tasks(tasks)
        self.write_backlog(tasks)
        next_events = [self._backlog_event(task, event) for task in tasks]
        self._log_decision(event, DECISION_SUCCESS, DECISION_REASON_CREATED_BACKLOG)
        self.remember_workflow(
            workflow_name=clean_description[:MAX_WORKFLOW_NAME_LENGTH],
            steps=[task.title for task in tasks],
            success_rate=DEFAULT_WORKFLOW_SUCCESS_RATE,
        )
        return AgentResult(
            success=True,
            output={OUTPUT_KEY_TASKS: [asdict(task) for task in tasks]},
            next_events=next_events,
        )

    def parse_tasks(self, model_output: str) -> List[Task]:
        """Parse model JSON output into deterministic Task objects."""
        try:
            parsed_output = json.loads(model_output)
        except json.JSONDecodeError as error:
            raise ValueError(str(error)) from error

        task_items = self._extract_task_items(parsed_output)
        date_stamp = _date_stamp()
        next_sequence = self._next_task_sequence(date_stamp)
        original_to_deterministic_ids = self._task_id_map(
            task_items,
            date_stamp,
            next_sequence,
        )
        created_at = _utc_timestamp()
        return [
            self._task_from_item(
                task_item,
                self._task_id(date_stamp, next_sequence + offset),
                original_to_deterministic_ids,
                created_at,
            )
            for offset, task_item in enumerate(task_items)
        ]

    def write_backlog(self, tasks: Sequence[Task]) -> None:
        """Append generated tasks to backlog.md in markdown format."""
        if not tasks:
            return
        backlog_content = self._render_backlog(tasks)
        _append_atomically(self._backlog_path, backlog_content)

    def _consult_for_extra_large_tasks(self, tasks: Sequence[Task]) -> None:
        """Ask code review to validate XL planning tasks."""
        for task in tasks:
            if task.complexity != COMPLEXITY_EXTRA_LARGE:
                continue
            answer = self.consult(
                target_agent=TARGET_CODE_REVIEW_AGENT,
                question="Is this task decomposition implementable as written?",
                context=task.to_markdown(),
                consultation_type=ConsultationType.FEASIBILITY_CHECK,
            )
            if answer and self._answer_flags_implementability_risk(answer):
                task.acceptance_criteria.append(
                    f"{IMPLEMENTABILITY_WARNING_PREFIX} {answer[:REVIEW_NOTE_LIMIT]}"
                )

    def _answer_flags_implementability_risk(self, answer: str) -> bool:
        """Return True when a consultation answer identifies task risk."""
        normalized_answer = answer.lower()
        return (
            NOT_IMPLEMENTABLE_TEXT in normalized_answer
            or MISSING_TEXT in normalized_answer
        )

    @property
    def _backlog_path(self) -> Path:
        """Return the project backlog path."""
        return self.project_root / BACKLOG_FILE_NAME

    @property
    def _decisions_log_path(self) -> Path:
        """Return the project decisions log path."""
        return self.project_root / DECISIONS_LOG_NAME

    def _build_prompt(
        self,
        description: str,
        project_context: Optional[str],
        codebase_context: Optional[str] = None,
    ) -> str:
        """Build the model prompt from feature description and context."""
        prompt_parts = [
            f"{PROMPT_DESCRIPTION_LABEL}\n{description}",
            PROMPT_INSTRUCTION,
        ]
        if project_context and project_context.strip():
            prompt_parts.insert(
                1,
                f"{PROMPT_CONTEXT_LABEL}\n{project_context.strip()}",
            )
        if codebase_context and codebase_context.strip():
            prompt_parts.insert(
                -1,
                f"{PROMPT_CODEBASE_CONTEXT_LABEL}\n{codebase_context.strip()}",
            )
        return PROMPT_SECTION_SEPARATOR.join(prompt_parts)


    def _extract_task_items(self, parsed_output: Any) -> List[Mapping[str, Any]]:
        """Extract task mappings from supported JSON shapes."""
        if isinstance(parsed_output, Mapping):
            parsed_output = parsed_output.get(MODEL_KEY_TASKS)
        if not isinstance(parsed_output, list):
            raise ValueError(DECISION_REASON_INVALID_JSON)
        if not all(isinstance(task_item, Mapping) for task_item in parsed_output):
            raise ValueError(DECISION_REASON_INVALID_JSON)
        return list(parsed_output)

    def _next_task_sequence(self, date_stamp: str) -> int:
        """Return the next deterministic sequence number for today's tasks."""
        if not self._backlog_path.exists():
            return 1
        prefix = self._task_id_prefix(date_stamp)
        highest_sequence = 0
        for line in self._backlog_path.read_text(encoding=ENCODING).splitlines():
            if prefix not in line:
                continue
            sequence = self._sequence_from_line(line, prefix)
            highest_sequence = max(highest_sequence, sequence)
        return highest_sequence + 1

    def _sequence_from_line(self, line: str, prefix: str) -> int:
        """Extract a task sequence from a backlog heading line."""
        start_index = line.find(prefix)
        if start_index < 0:
            return 0
        sequence_start = start_index + len(prefix)
        sequence_text = line[sequence_start : sequence_start + TASK_SEQUENCE_WIDTH]
        return int(sequence_text) if sequence_text.isdigit() else 0

    def _task_id_map(
        self,
        task_items: Sequence[Mapping[str, Any]],
        date_stamp: str,
        next_sequence: int,
    ) -> Mapping[str, str]:
        """Map model task IDs to deterministic ProjectOS task IDs."""
        id_map = {}
        for offset, task_item in enumerate(task_items):
            deterministic_id = self._task_id(date_stamp, next_sequence + offset)
            original_id = task_item.get(MODEL_KEY_ID)
            if isinstance(original_id, str) and original_id:
                id_map[original_id] = deterministic_id
            id_map[deterministic_id] = deterministic_id
        return id_map

    def _task_from_item(
        self,
        task_item: Mapping[str, Any],
        deterministic_id: str,
        id_map: Mapping[str, str],
        created_at: str,
    ) -> Task:
        """Convert one model task mapping into a Task dataclass."""
        blocked_by = self._optional_string(task_item.get(MODEL_KEY_BLOCKED_BY))
        return Task(
            id=deterministic_id,
            title=self._required_string(task_item, MODEL_KEY_TITLE),
            type=self._normalized_choice(
                task_item.get(MODEL_KEY_TYPE),
                VALID_TASK_TYPES,
                DEFAULT_TASK_TYPE,
            ).lower(),
            priority=self._normalized_choice(
                task_item.get(MODEL_KEY_PRIORITY),
                VALID_PRIORITIES,
                DEFAULT_PRIORITY,
            ).upper(),
            complexity=self._normalized_choice(
                task_item.get(MODEL_KEY_ESTIMATED_COMPLEXITY)
                or task_item.get(MODEL_KEY_COMPLEXITY),
                VALID_COMPLEXITIES,
                DEFAULT_COMPLEXITY,
            ).upper(),
            dependencies=self._remapped_dependencies(task_item, id_map),
            acceptance_criteria=self._string_list(
                task_item.get(MODEL_KEY_ACCEPTANCE_CRITERIA)
            ),
            agent_assignment=self._string_or_default(
                task_item.get(MODEL_KEY_AGENT_ASSIGNMENT),
                DEFAULT_AGENT_ASSIGNMENT,
            ),
            blocked_by=blocked_by,
            file_path=self._optional_string(task_item.get(MODEL_KEY_FILE_PATH)),
            created_at=created_at,
            status=TASK_STATUS_BLOCKED if blocked_by else TASK_STATUS_PENDING,
        )

    def _task_id(self, date_stamp: str, sequence_number: int) -> str:
        """Build a deterministic ProjectOS planning task ID."""
        sequence_text = str(sequence_number).zfill(TASK_SEQUENCE_WIDTH)
        return (
            f"{TASK_ID_PREFIX}{TASK_ID_SEPARATOR}{date_stamp}"
            f"{TASK_ID_SEPARATOR}{sequence_text}"
        )

    def _task_id_prefix(self, date_stamp: str) -> str:
        """Return the deterministic task ID prefix for a date."""
        return f"{TASK_ID_PREFIX}{TASK_ID_SEPARATOR}{date_stamp}{TASK_ID_SEPARATOR}"

    def _required_string(self, task_item: Mapping[str, Any], key: str) -> str:
        """Return a non-empty task string field or raise ValueError."""
        value = task_item.get(key)
        if not isinstance(value, str) or not value.strip():
            raise ValueError(DECISION_REASON_INVALID_JSON)
        return value.strip()

    def _optional_string(self, value: Any) -> Optional[str]:
        """Return an optional trimmed string value."""
        if value is None:
            return None
        if isinstance(value, str) and value.strip():
            return value.strip()
        return None

    def _string_or_default(self, value: Any, default: str) -> str:
        """Return a trimmed string value or a default."""
        if isinstance(value, str) and value.strip():
            return value.strip()
        return default

    def _normalized_choice(
        self,
        value: Any,
        valid_values: Iterable[str],
        default: str,
    ) -> str:
        """Normalize a string enum-like value against allowed values."""
        if not isinstance(value, str) or not value.strip():
            return default
        valid_lookup = {
            valid_value.upper(): valid_value for valid_value in valid_values
        }
        normalized_value = value.strip().upper()
        return valid_lookup.get(normalized_value, default)

    def _string_list(self, value: Any) -> List[str]:
        """Return a list of non-empty strings from a model value."""
        if not isinstance(value, list):
            return []
        return [
            item.strip()
            for item in value
            if isinstance(item, str) and item.strip()
        ]

    def _remapped_dependencies(
        self,
        task_item: Mapping[str, Any],
        id_map: Mapping[str, str],
    ) -> List[str]:
        """Return dependencies with model IDs remapped to deterministic IDs."""
        dependencies = self._string_list(task_item.get(MODEL_KEY_DEPENDENCIES))
        return [id_map.get(dependency, dependency) for dependency in dependencies]

    def _render_backlog(self, tasks: Sequence[Task]) -> str:
        """Render tasks in the required markdown backlog format."""
        lines = self._backlog_preamble()
        for priority in (PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW):
            priority_tasks = [task for task in tasks if task.priority == priority]
            if not priority_tasks:
                continue
            lines.extend(self._render_priority_section(priority, priority_tasks))
        return NEWLINE.join(lines).rstrip() + NEWLINE

    def _backlog_preamble(self) -> List[str]:
        """Return the backlog header when needed before appending tasks."""
        if self._backlog_path.exists() and self._backlog_path.read_text(
            encoding=ENCODING
        ):
            return [
                EMPTY_TEXT,
                f"{BACKLOG_LAST_UPDATED_LABEL} {_utc_timestamp()}",
                EMPTY_TEXT,
            ]
        return [
            BACKLOG_TITLE,
            f"{BACKLOG_LAST_UPDATED_LABEL} {_utc_timestamp()}",
            EMPTY_TEXT,
        ]

    def _render_priority_section(
        self,
        priority: str,
        tasks: Sequence[Task],
    ) -> List[str]:
        """Render one priority section of backlog tasks."""
        lines = [BACKLOG_PRIORITY_HEADING_TEMPLATE.format(priority=priority)]
        for task in tasks:
            lines.extend(self._render_task(task))
        return lines

    def _render_task(self, task: Task) -> List[str]:
        """Render one task in structured markdown."""
        dependencies = (
            ", ".join(task.dependencies) if task.dependencies else BACKLOG_NONE_VALUE
        )
        lines = [
            EMPTY_TEXT,
            BACKLOG_TASK_HEADING_TEMPLATE.format(task_id=task.id, title=task.title),
            f"{BACKLOG_TYPE_LABEL} {task.type}",
            f"{BACKLOG_COMPLEXITY_LABEL} {task.complexity}",
            f"{BACKLOG_AGENT_LABEL} {task.agent_assignment}",
            BACKLOG_ACCEPTANCE_LABEL,
        ]
        lines.extend(
            f"{BACKLOG_CHECKLIST_PREFIX} {criterion}"
            for criterion in task.acceptance_criteria
        )
        lines.extend(
            [
                f"{BACKLOG_DEPENDENCIES_LABEL} {dependencies}",
                f"{BACKLOG_STATUS_LABEL} {task.status}",
            ]
        )
        if task.blocked_by:
            lines.append(f"{BACKLOG_BLOCKED_BY_LABEL} {task.blocked_by}")
        return lines

    def _backlog_event(self, task: Task, parent_event: AgentEvent) -> AgentEvent:
        """Create a BACKLOG_CHANGED event for a generated task."""
        payload = asdict(task)
        if task.file_path is None:
            payload.pop(PAYLOAD_KEY_FILE_PATH, None)
        payload[PAYLOAD_KEY_TASK_ID] = task.id
        payload[PAYLOAD_KEY_TASK_DESCRIPTION] = task.title
        payload[PAYLOAD_KEY_TASK_TYPE] = task.type
        payload[PAYLOAD_KEY_TARGET_AGENT] = task.agent_assignment
        return AgentEvent(
            event_type=EventType.BACKLOG_CHANGED,
            source_agent=self.name,
            payload=payload,
            correlation_id=parent_event.correlation_id or parent_event.event_id,
            blocked_by=task.blocked_by,
            priority=self._event_priority(task.priority),
        )

    def _event_priority(self, priority: str) -> EventPriority:
        """Convert task priority text to EventPriority."""
        if priority == PRIORITY_HIGH:
            return EventPriority.HIGH
        if priority == PRIORITY_LOW:
            return EventPriority.LOW
        return EventPriority.MEDIUM

    def _failure_result(self, event: AgentEvent, reason: str) -> AgentResult:
        """Log and return a non-crashing failure result."""
        self._log_decision(event, DECISION_FAILURE, reason)
        return AgentResult(
            success=False,
            output={OUTPUT_KEY_ERROR: reason},
        )

    def _log_decision(self, event: AgentEvent, outcome: str, reasoning: str) -> None:
        """Append one Planning Agent decision to decisions.log."""
        timestamp = _utc_timestamp()
        decision_line = (
            f"{DECISION_LOG_PREFIX}{timestamp}{DECISION_LOG_SEPARATOR}"
            f"{event.event_id}{DECISION_LOG_SEPARATOR}"
            f"{outcome}{DECISION_LOG_SEPARATOR}"
            f"{reasoning}{DECISION_LOG_SUFFIX}"
        )
        _append_atomically(self._decisions_log_path, decision_line)
        self.log_decision(reasoning, outcome)


__all__ = ["PlanningAgent", "Task"]
